# This is a basic workflow to help you get started with Actions

name: PyInstaller Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: PyInstaller Linux Build
        run: |
          pyinstaller --onefile --clean --name combahton_cli -y ${{ github.workspace }}/src/__main__.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: combahton_cli_linux_amd64
          path: ${{ github.workspace }}/dist/

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          # GitHub secret token
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Should this release be marked as a draft?
          draft: true
          # Should this release be marked as a pre-release?
          prerelease: false
          automatic_release_tag: latest
          # Assets to upload to the release
          files: ${{ github.workspace }}/dist/
